### ISSUE TITLE
请问测试支持爬那些网站呢

### ISSUE THREAD

**Issue by NicodeLee** [yijingping/unicrawler#3]

**Comment by yijingping** [comment]
大部分网站都支持。只要有列表页-详情页，就能爬。
下面我配置爬取的一些站点：
![image](https://cloud.githubusercontent.com/assets/2122123/22874937/c29afec0-f203-11e6-9d37-b3f7c6a6c368.png)

爬取的内容已经注入到站点PySpace：
http://py.bowenpay.com/topics/?page=555

**Comment by 7rack** [comment]
@yijingping  可否增加一个简单的例子，感谢。在配置的时候不是特别清楚，比如数据库这块
```json
{
  "kind":"mysql",
  "database":{
    "host":"127.0.0.1",
    "name":"test",
    "user":"root",
    "password":"123456",
    "charset":"utf-8"
  },
  "table":"testtbl",
  "defaults":"",
  "unique_key":""
}
```
`索引url列表` 也没配置成功。:  尝试了几次都没有数据 :(

**Comment by yijingping** [comment]
已微信回复
