### ISSUE TITLE
后台里怎么配置索引和规则才能开始爬取数据，能否有个简单的使用文档

### ISSUE THREAD

**Issue by luowenyue** [yijingping/unicrawler#6]
或者举个例子演示一下使用，谢谢

**Comment by yijingping** [comment]
现在文档还没有写， 你可以登录这个网址看看demo  http://unicrawler.bowenpay.com/ testuser 123456

**Comment by luowenyue** [comment]
@yijingping 好的非常感谢。

**Comment by vnx6fpcs** [comment]
网站好像挂了，能不能更新一个教程，不会配置相关规则
